#
# Copyright © 2019-today Peter M. Stahl pemistahl@gmail.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expressed or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Rust Release

on:
  push:
    tags:
      - v1.*

jobs:
  rust-release:
    name: ${{ matrix.name }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: Linux Binaries
            x86_64-target: x86_64-unknown-linux-musl
            aarch64-target: aarch64-unknown-linux-musl

          - os: macos-latest
            name: MacOS Binaries
            x86_64-target: x86_64-apple-darwin
            aarch64-target: aarch64-apple-darwin

          - os: windows-latest
            name: Windows Binaries
            x86_64-target: x86_64-pc-windows-msvc
            aarch64-target: aarch64-pc-windows-msvc

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Add rustup x86_64 target
        run: rustup target add ${{ matrix.x86_64-target }}

      - name: Add rustup aarch64 target
        run: rustup target add ${{ matrix.aarch64-target }}

      - name: Build x86_64 target in release mode
        run: cargo build --release --target ${{ matrix.x86_64-target }} --locked

      - name: Build aarch64 target in release mode
        run: cargo build --release --target ${{ matrix.aarch64-target }} --locked

      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Create x86_64 zip file on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install zip
          cd target/${{ matrix.x86_64-target }}/release
          zip grex-${{ steps.get_version.outputs.version }}-${{ matrix.x86_64-target }}.zip grex.exe
          cd ../../..

      - name: Create aarch64 zip file on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd target/${{ matrix.aarch64-target }}/release
          zip grex-${{ steps.get_version.outputs.version }}-${{ matrix.aarch64-target }}.zip grex.exe
          cd ../../..

      - name: Create x86_64 tar.gz file on Linux and macOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          chmod +x target/${{ matrix.x86_64-target }}/release/grex
          tar -zcf target/${{ matrix.x86_64-target }}/release/grex-${{ steps.get_version.outputs.version }}-${{ matrix.x86_64-target }}.tar.gz -C target/${{ matrix.x86_64-target }}/release grex

      - name: Create aarch64 tar.gz file on Linux and macOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          chmod +x target/${{ matrix.aarch64-target }}/release/grex
          tar -zcf target/${{ matrix.aarch64-target }}/release/grex-${{ steps.get_version.outputs.version }}-${{ matrix.aarch64-target }}.tar.gz -C target/${{ matrix.aarch64-target }}/release grex

      - name: Upload release and assets to GitHub
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          release_name: grex ${{ steps.get_version.outputs.version }}
          file_glob: true
          file: target/*/release/grex-${{ steps.get_version.outputs.version }}-*.{zip,tar.gz}

  release-upload:
    name: Upload to crates.io
    needs: rust-release

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Upload release to crates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
